services:
  app:
    build: .
    command: python3 -u api.py
    ports:
      - "5050:5050"
    volumes:
      - .:/talkative_app
    environment:
      - API_KEY=${API_KEY}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
      - MONGO_AUTH_SRC=${MONGO_AUTH_SRC}
    links:
      - db
  db:
    image: mongo:latest
    hostname: talkative_mongodb
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017